# Generated by Django 5.0.14 on 2026-05-30 18:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "position",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="职位"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                ("bio", models.TextField(blank=True, default="", verbose_name="简介")),
                (
                    "contact",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="联系方式"
                    ),
                ),
                (
                    "contact_public",
                    models.BooleanField(default=False, verbose_name="公开联系方式"),
                ),
                (
                    "skills",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="技能标签"
                    ),
                ),
                (
                    "joined_at",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="加入时间"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="展示中")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "成员",
                "verbose_name_plural": "成员",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="显示名称"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "管理员"), ("editor", "编辑者")],
                        default="editor",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="内容"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("news", "新闻"),
                            ("course", "课程"),
                            ("exam", "考核"),
                        ],
                        default="news",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="已发布"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="奖项名称")),
                (
                    "competition",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="竞赛名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("grand", "特等奖"),
                            ("first", "一等奖"),
                            ("second", "二等奖"),
                            ("third", "三等奖"),
                            ("merit", "优胜奖"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="等级",
                    ),
                ),
                (
                    "award_date",
                    models.DateField(blank=True, null=True, verbose_name="获奖日期"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="awards/", verbose_name="证书照片"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="awards",
                        to="core.member",
                        verbose_name="获奖成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "奖项",
                "verbose_name_plural": "奖项",
                "ordering": ["order", "-award_date"],
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="uploads/%Y/%m/", verbose_name="文件"),
                ),
                (
                    "original_name",
                    models.CharField(max_length=500, verbose_name="原始文件名"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("learning", "学习资料"),
                            ("project", "项目代码"),
                            ("circuit", "电路设计"),
                            ("firmware", "固件"),
                            ("video", "教学视频"),
                            ("tool", "软件工具"),
                            ("installer", "系统镜像"),
                        ],
                        default="learning",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="描述"
                    ),
                ),
                (
                    "sha256_hash",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="SHA256"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="公开下载"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件",
                "verbose_name_plural": "文件",
                "ordering": ["-created_at"],
            },
        ),
    ]
